import Head from "next/head";
import styles from "@/styles/Home.module.css";
import SearchBar from "@/components/searchBar";
import TopRated from "@/components/topRated";
import ForYou from "@/components/forYou";

export default function Home() {
  //array momentaneo per vedere qualcosa
  const books = [
    { title: "To Kill a Mockingbird", author: "Harper Lee" },
    { title: "1984", author: "George Orwell" },
    { title: "Pride and Prejudice", author: "Jane Austen" },
  ];
  return (
    <>
      <Head>
        <title>Mark your Books</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>
          <SearchBar />
          <TopRated books={books} />
          <ForYou books={books} />
        </main>
      </div>
    </>
  );
}
